New Compiler API Migration
ballerina-platform/module-ballerinax-azure.functions pull request #101
Opened 2021-03-15 10:19 UTC by xlight05

## Purpose
Earlier, Azure functions works by modifying the AST using PackageNode block in compiler extensions. In this PR we completely avoid editing the AST generating an additional document for generated handler functions instead.

This PR also introduces two levels of additional testing
1. Syntax Tree validation by comparing generated nodes.
2. Runtime validation using mocking http calls of azure functions
## Approach
We iterate through the functions annotated as azure functions and generate intermediate handler functions as to simply the user experience. The generated functions will be written as a separate documented and `Project` will be modified accordingly.

2021-03-16 06:41 UTC, anupama-pathirage commented
@xlight05 The commit messages and PR heading is not according to the best practices. Please correct them.

A properly formed Git commit subject line should always be able to complete the following sentence:

If applied, this commit will **_your subject line here_**

Refer [1] for more details.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

2021-03-31 03:27 UTC, anuruddhal requested changes

2021-03-31 03:27 UTC, anuruddhal commented on azurefunctions-extension-test/src/test/resources/handlers/code/main.bal
> +// Copyright (c) 2020 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Fix the header.

2021-03-31 03:27 UTC, anuruddhal commented on azurefunctions-extension-test/src/test/java/org/ballerinax/azurefunctions/test/HandlerTest.java
> +                    if (document.name().equals("main.bal")) {
Constant should come first.

2021-03-31 03:27 UTC, anuruddhal commented on azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionVisitor.java
> +        if (!orgName.equals("ballerinax")) {
Constant should come first.

2021-03-31 03:27 UTC, anuruddhal commented on azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionVisitor.java
> +        if (moduleName.equals("azure_functions")) {
Constant should come first.

2021-04-01 08:01 UTC, merged