Implement HTTP typed resource responses
ballerina-platform/module-ballerinax-azure.functions pull request #489
Opened 2022-08-01 10:23 UTC by Thevakumar-Luheerathan

## Purpose
> resolves #478 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2022-08-01 10:36 UTC, anuruddhal requested changes

2022-08-01 10:36 UTC, anuruddhal commented on ballerina-tests/main.bal
> +          }
Shall we fix formatting issues?

2022-08-01 10:36 UTC, anuruddhal commented on ballerina/http_status_code_types.bal
> +// Copyright (c) 2021 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Fix license header hear

2022-08-01 10:36 UTC, anuruddhal commented on native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
> +        } else if (this.annotations.get(0).equals("HTTPOutput")) {
Make constant as the first argument
```java
"HTTPOutput".equals(this.annotations.get(0))
```

2022-08-01 10:41 UTC, xlight05 requested changes

2022-08-01 10:41 UTC, xlight05 commented on native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
> +                BObject status = (BObject) (((BMap) result).get(StringUtils.fromString("status")));
Shall we extract the `(BMap) result` into a variable?

2022-08-01 10:41 UTC, xlight05 commented on native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
> +                if (((BMap) result).containsKey(StringUtils.fromString("headers"))) {
shall we extract this(and other) complex logic into a function to improve the readability?

2022-08-01 10:41 UTC, xlight05 commented on native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
> +                        ((BMap) headers).put(StringUtils.fromString("content-type"),
shall we extract the converted headers bmap into a variable?

2022-08-01 10:41 UTC, xlight05 commented on native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
> +                        ((BMap) headers).put(StringUtils.fromString("content-type"),
shouldn't we do the check after converting content-type to lowercase? (to account for caps issues)

2022-08-01 10:41 UTC, xlight05 commented on ballerina-tests/tests/test.bal
> +   json resp = check clientEndpoint->post("/post-hello-httpResTest1", readJson);
do we need to introduce multiple jsons? can't we reuse existing json we have, and reuse it in the test cases?

2022-08-02 07:27 UTC, xlight05 commented on native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
> +    private static final String QUEUE_OUTPUT = "QueueOutput";
Shall we move these into Constants Class?

2022-08-02 07:28 UTC, xlight05 approved these changes

2022-08-03 03:09 UTC, merged